/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
//{ title: '', genres:'', description:'', main_character: '', year_released:'', poster:''},
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('movie_list').del()
  await knex('movie_list').insert([
    { title: 'Rogue One: A Star Wars Story', genres:'Action Epic, Adventure Epic, Epic, Psychological Drama, Quest, Sci-Fi Epic, Space Sci-Fi', description:"In a time of conflict, a group of unlikely heroes band together on a mission to steal the plans to the Death Star, the Empire's ultimate weapon of destruction.", main_character: 'Jyn Erso', year_released:'2016-12-16', poster:'https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_FMjpg_UX1000_.jpg'}, //YYYY-MM-DD
    { title: 'Dune', genres:'Action Epic, Adventure Epic, Desert Adventure, Epic, Sci-Fi Epic, Space Sci-Fi', description:'Paul Atreides arrives on Arrakis after his father accepts the stewardship of the dangerous planet. However, chaos ensues after a betrayal as forces clash to control melange, a precious resource.', main_character: 'Paul Atreides', year_released:'2021-10-22', poster:'https://m.media-amazon.com/images/M/MV5BNWIyNmU5MGYtZDZmNi00ZjAwLWJlYjgtZTc0ZGIxMDE4ZGYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'},
    { title: 'Dune: Part Two', genres:'Action Epic, Adventure Epic, Desert Adventure, Epic, Sci-Fi Epic, Space Sci-Fi', description:'Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.', main_character: 'Paul Atreides', year_released:'2024-03-01', poster:'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'},
    { title: 'Uma Musume: Pretty Derby - Beginning of a New Era', genres:'Japanese, Anime, Hand-Drawn Animation Animation, Comedy, Drama, Sport', description:'Uma Musume - they were born to run. Born with names from other worlds, sometimes with strange, sometimes with glorious histories, they inherit the souls of these names and run. Aiming only at the goal beyond our eyes.', main_character: 'Jungle Pocket', year_released:'2026-02-27', poster:'https://m.media-amazon.com/images/M/MV5BNmI1ZDI0OGEtY2JjYS00MWQyLWI5ZTctMTg4ODI0YTMyZGU5XkEyXkFqcGc@._V1_.jpg'},
    { title: '1917', genres:'Epic, Period Drama, War Epic, Action, Drama, War', description:'April 6th, 1917. As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.', main_character: 'Lance Corporal Schofield', year_released:'2019-12-25', poster:'https://m.media-amazon.com/images/S/pv-target-images/932895b085677a859bca8e22deca44e376a0bcbc80879ae6d7a0a1048c7fc7fa.jpg'},
    { title: 'Dawn Of The Planet Of The Apes', genres:'Dystopian Sci-Fi, Action, Adventure, Drama, Sci-Fi, Thriller', description:'The fragile peace between apes and humans is threatened as mistrust and betrayal threaten to plunge both tribes into a war for dominance over the Earth.', main_character: 'Caesar', year_released:'2014-06-26', poster:'https://m.media-amazon.com/images/M/MV5BNWNjYzQ4ZGItZTg1My00NTM2LTg1NDUtYThjOTQwMTYyNjU1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg'},
    { title: 'Project Hail Mary', genres:'Dark Comedy, Epic, Sci-Fi Epic, Space Sci-Fi, Drama, SCi-Fi, Thriller', description:"A science teacher wakes up alone on a spaceship. As his memory returns, he uncovers a mission to stop a mysterious substance killing Earth's sun and that an unexpected friendship may be the key.", main_character: 'Ryan Gosling', year_released:'2026-04-20', poster:'https://m.media-amazon.com/images/M/MV5BNTkwNzJiYTctNzI3NC00NjE1LTlhYjktY2Q5MTdmMWFmNzcxXkEyXkFqcGc@._V1_.jpg'},
    { title: 'Interstellar', genres:'Adventure Epic, Epic, Psychological Drama, Quest, Sci-Fi Epic, Space Sci-Fi, Time Travel', description:'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.', main_character: 'Cooper', year_released:'2014-10-26', poster:'https://m.media-amazon.com/images/I/71JC2qvPx5L._AC_UF894,1000_QL80_.jpg'},
    { title: '', genres:'Period Drama, Psychological Drama, Action, Drama, War', description:'A grizzled tank commander makes tough decisions as he and his crew fight their way across Germany in April, 1945.', main_character: 'Norman Ellison', year_released:'2014-10-15', poster:'https://m.media-amazon.com/images/I/71Ma-G5VcZL._AC_UF894,1000_QL80_.jpg'},
  ]);
};
